// Copyright © 2019 Ivan Kravarščan. All rights reserved. Licensed under the 
// LGPL License. See License.txt in the project root for license information.

namespace Ikadn
{
	/// <summary>
	/// Interface for IKADN object factories usable by IKADN parser.
	/// </summary>
	public interface IIkadnObjectFactory
	{
		/// <summary>
		/// Character that identifies an object parcable by the factory.
		/// </summary>
		char Sign { get; }

		/// <summary>
		/// Parses input for an IKADN object.
		/// </summary>
		/// <param name="parser">IKADN parser instance.</param>
		/// <returns>IKADN object generated by factory.</returns>
		IkadnBaseObject Parse(IkadnParser parser);
	}
}
