namespace Ikadn
{
	/// <summary>
	/// Interface for IKADN value factories usable by IKADN parser.
	/// </summary>
	public interface IValueFactory
	{
		/// <summary>
		/// Character that identifies value parcable by factory.
		/// </summary>
		char Sign { get; }

		/// <summary>
		/// Parses input for a IKADN value.
		/// </summary>
		/// <param name="parser">IKADN parser instance.</param>
		/// <returns>IKADN value generated by factory.</returns>
		IkadnBaseValue Parse(Parser parser);
	}
}
