using Ikadn;
using Ikadn.Ikon.Values;
using Ikadn.Utilities;
using System;

namespace Ikadn.Ikon.Factories
{
	/// <summary>
	/// IKADN value factory for composite IKON values.
	/// </summary>
	public class ObjectFactory : IIkadnObjectFactory
	{
		/// <summary>
		/// Sign for IKADN composite value.
		/// </summary>
		public const char OpeningSign = '{';

		/// <summary>
		/// Closing character for IKON composite value in textual
		/// representation.
		/// </summary>
		public const char ClosingChar = '}';

		/// <summary>
		/// Sign for IKADN composite value.
		/// </summary>
		public char Sign
		{
			get { return OpeningSign; }
		}

		/// <summary>
		/// Parses input for a IKADN value.
		/// </summary>
		/// <param name="parser">IKADN parser instance.</param>
		/// <returns>IKADN value generated by factory.</returns>
		public IkadnBaseObject Parse(Ikadn.IkadnParser parser)
		{
			if (parser == null)
				throw new System.ArgumentNullException("parser");

			ObjectValue res = new ObjectValue(Ikadn.Ikon.Parser.ReadIdentifier(parser.Reader));

			while (parser.Reader.PeekNextNonwhite() != ClosingChar)
			{
				string memberName = Ikadn.Ikon.Parser.ReadIdentifier(parser.Reader);
				
				string startPosition = parser.Reader.PositionDescription;
				if (parser.HasNext())
					res[memberName] = parser.ParseNext();
				else
					throw new FormatException("Characters from " + startPosition + " to " + parser.Reader.PositionDescription + " couldn't be parsed as IKADN value");
			}
			parser.Reader.Read();

			return res;
		}
	}
}
