using Ikon;
using Ikon.Ston.Values;
using Ikon.Utilities;
using System;

namespace Ikon.Ston.Factories
{
	/// <summary>
	/// IKON value factory for composite IKSTON values.
	/// </summary>
	public class ObjectFactory : IValueFactory
	{
		/// <summary>
		/// Sign for IKON composite value.
		/// </summary>
		public const char OpeningSign = '{';

		/// <summary>
		/// Closing character for IKSTON composite value in textual
		/// representation.
		/// </summary>
		public const char ClosingChar = '}';

		/// <summary>
		/// Sign for IKON composite value.
		/// </summary>
		public char Sign
		{
			get { return OpeningSign; }
		}

		/// <summary>
		/// Parses input for a IKON value.
		/// </summary>
		/// <param name="parser">IKON parser instance.</param>
		/// <returns>IKON value generated by factory.</returns>
		public IkonBaseValue Parse(Ikon.Parser parser)
		{
			if (parser == null)
				throw new System.ArgumentNullException("parser");

			ObjectValue res = new ObjectValue(Ikon.Ston.Parser.ReadIdentifier(parser.Reader));

			while (parser.Reader.PeekNextNonwhite() != ClosingChar)
			{
				string memberName = Ikon.Ston.Parser.ReadIdentifier(parser.Reader);
				
				string startPosition = parser.Reader.PositionDescription;
				if (parser.HasNext())
					res[memberName] = parser.ParseNext();
				else
					throw new FormatException("Characters from " + startPosition + " to " + parser.Reader.PositionDescription + " couldn't be parsed as IKON value");
			}
			parser.Reader.Read();

			return res;
		}
	}
}
